# Generated by Django 5.2.17 on 2026-09-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('video_key', models.CharField(blank=True, db_index=True, default='', max_length=500)),
                ('video_size', models.BigIntegerField(default=0)),
                ('sealed_state', models.CharField(blank=True, default='', max_length=10)),
                ('sealed_playlist', models.TextField(blank=True, default='')),
                ('sealed_key', models.BinaryField(blank=True, null=True)),
                ('sealed_error', models.CharField(blank=True, default='', max_length=300)),
                ('title', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
