# Generated by Django 4.2.30 on 2026-09-29 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchProgress',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('video_type', models.CharField(max_length=100)),
                ('video_id', models.CharField(max_length=64)),
                ('seconds_watched', models.FloatField(default=0)),
                ('position', models.FloatField(default=0)),
                ('duration', models.FloatField(default=0)),
                ('buckets', models.JSONField(blank=True, default=list)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='vidlock_progress',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'watch progress',
                'verbose_name_plural': 'watch progress',
                'indexes': [models.Index(fields=['video_type', 'video_id'], name='vidlock_progress_video')],
            },
        ),
        migrations.AddConstraint(
            model_name='watchprogress',
            constraint=models.UniqueConstraint(
                fields=('user', 'video_type', 'video_id'), name='vidlock_progress_once'
            ),
        ),
    ]
