# Generated by Django 4.2.30 on 2026-09-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidlock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('video_type', models.CharField(max_length=100)),
                ('video_id', models.CharField(max_length=64)),
                ('language', models.CharField(blank=True, default='', max_length=16)),
                ('segments', models.JSONField(blank=True, default=list)),
                ('text', models.TextField(blank=True, default='')),
                ('search_text', models.TextField(blank=True, default='', editable=False)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='transcript',
            constraint=models.UniqueConstraint(
                fields=('video_type', 'video_id'), name='vidlock_transcript_once'
            ),
        ),
    ]
